---
output: html_document
---
<!--introduction-->

Colorimetry, in which a sample absorbs visible light, is one example of a spectroscopic method of analysis. An early application of a colorimetry is Nessler’s method for ammonia, NH~3~, first introduced in the 1850s. Nessler found that adding an alkaline solution of HgI~2~ and KI to a dilute solution of ammonia produced a yellow-to-reddish brown colloid, in which the colloid’s color depended on the concentration of ammonia. By visually comparing the color of a sample to the colors of a series of standard solutions of NH~3~, Nessler was able to determine the concentration of ammonia in the sample.

The figure in the upper-right corner shows Nessler’s method for comparing the color of two solutions. Natural light was passed through equal heights of the samples and the standards, held in identical tubes. The analyst viewed the solutions by looking down toward the light source. The view from the top is what the analyst saw. To determine the analyte’s concentration, the analyst exchanged standards until the two colors matched.

The figure in the lower-right corner is a Spectronic 20D+, a simple instrument that accomplishes the same thing as looking through a pair of Nessler tubes. A source of light is passed through a monochromator that isolates a narrow range of wavelengths to pass through a sample or a reference blank. The detector is a photomultiplier tube. In both approaches, what we report is the amount of light absorbed by the sample. 
