---
output: html_fragment
---

<!-- text for activity 1 -->

The figure on the right is a simple model to help you think about the relationship between $T$, $P_T$ and $P_0$. The sample is placed in a rectangular cuvette (see photo) with a base that is 1 cm by 1 cm. Light enters one side of the cuvette and exits the opposite side. We are interested only in an infinitesimally thin cross-section parallel to the base, as shown by the black lines on the cuvette and the box below the cuvette. We let $1000$ photons enter the left-side of the cuvette at the same time. As a photon moves from left-to-right, its probability of being absorbed is set by the slider. After $50$ steps, the number of photons that exit the cuvette on the right is $P_T$. Values of $P_0$ and $P_T$ are included in the figure.

**Exercise 1.** Set the type of visualization to "none" and gather values of $P_T$ for absorption probabilities of $0.00$, $0.04$, $0.08$, $0.12$, and $0.16$, and calculate the transmittance for each. Examine your data and identify any interesting patterns you see between the probability of absorption and the value of $P_T$. What is the largest and smallest possible value for $T$?

**Exercise 2.** A cross-section plot shows those photons not yet absorbed as they move from left-to-right through $50$ equally spaced intervals. Before you look at the cross-section plot, predict what you will see for absorption probabilities of $0.00$, $0.04$, $0.08$, $0.12$, and $0.16$. Check your predictions by examining the cross-section plots. 

**Exercise 3.** If you count the number of photons in each of a cross-section plot's equally spaced intervals---Don't try this as the points are too small!---then you can plot the number of photons as a function of the distance, $d$, traveled; this is a $P(d)$ vs. $d$ plot. Before your look at these plots, make a prediction about the shape of the plot for absorption probabilities of $0.00$, $0.04$, $0.08$, $0.12$, and $0.16$. Check your predictions by examining the $P(d)$ vs. $d$ plots.

**Exercise 4.** Set the absorption probability to $0.08$ and examine the $P(d)$ vs. $d$ plot. The first four values of $P_T$ are $1000$, $920$, $846$, and $779$ (rounded to the nearest integer). Show that these values of $P_T$ are correct.
